# Write your MySQL query statement below



/*
WITH CTE AS (
    SELECT PRODUCT_ID, MIN (YEAR) FROM SALES
                             GROUP BY PRODUCT_ID
)
SELECT S.PRODUCT_ID, S.YEAR AS FIRST_YEAR, S.QUANTITY, S.PRICE
FROM SALES S
JOIN CTE ON CTE.PRODUCT_ID = S.PRODUCT_ID AND S.YEAR = CTE.MINYEAR;
*/

WITH CTE AS(
    SELECT *, RANK() OVER(PARTITION BY PRODUCT_ID ORDER BY YEAR) AS RNK 
    FROM SALES
)

SELECT PRODUCT_ID, YEAR AS FIRST_YEAR, QUANTITY, PRICE
FROM CTE
WHERE RNK =1;
